### ISSUE TITLE
How to change Gmap Api key ?

### ISSUE THREAD

**Issue by masbenny** [mattwright324/youtube-geofind#21]
i have done change youtube api, but i want to change gmap api, where is directory files ?
the site will get error like this if don't used gmap api:

Oops! Something went wrong.

`{"readyState":4,"responseText":"{\n \"error\": {\n \"code\": 403,\n \"message\": \"Requests from referer `

**Comment by mattwright324** [comment]
You can find the Gmaps API key in the default layout
https://github.com/mattwright324/youtube-geofind/blob/master/_layouts/default.html#L36-L37

**Comment by masbenny** [comment]
i has done change ytube + gmap api, and directory set chmod 777.  but i still getting error, can tell me what is the problem ? thanks....


`{"readyState":4,"responseText":"{\n \"error\": {\n \"code\": 403,\n \"message\": \"Requests from referer https://jejagu.com/ are blocked.\",\n \"errors\": [\n {\n \"message\": \"Requests from referer https://jejagu.com/ are blocked.\",\n \"domain\": \"global\",\n \"reason\": \"forbidden\"\n }\n ],\n \"status\": \"PERMISSION_DENIED\"\n }\n}\n","responseJSON":{"error":{"code":403,"message":"Requests from referer https://jejagu.com/ are blocked.","errors":[{"message":"Requests from referer https://jejagu.com/ are blocked.","domain":"global","reason":"forbidden"}],"status":"PERMISSION_DENIED"}},"status":403,"statusText":"Forbidden"}`

**Comment by mattwright324** [comment]
Sure you changed the API keys? You would get that error using my keys because they are restricted to localhost and my domain `mattw.io` and wouldn't accept your domain.

YouTube API key is this script
https://github.com/mattwright324/youtube-geofind/blob/master/js/youtube-api-v3.js#L43

Maps key is at the bottom of each page from this layout
https://github.com/mattwright324/youtube-geofind/blob/master/_layouts/default.html#L36-L37

Check these for how to create your own key(s)
https://developers.google.com/youtube/v3/getting-started#intro
https://developers.google.com/maps/documentation/javascript/get-api-key

**Comment by masbenny** [comment]
1000% sure, i used yt+gmap api like in here :

yt-api  : https://jejagu.com/dl/
gmap-api : https://jejagu.com/nuklir/


ex; map leaflet :
https://jejagu.com/cuaca/
https://jejagu.com/gempa/

**Comment by masbenny** [comment]
**The problem is fixed:**
`1. rm -rf Gemfile.lock
2. rm -rf _site
3. bundle exec jekyll serve
4. change gmap - yt api
5. https://jejagu.com/ytgeo/`

**Comment by mattwright324** [comment]
Ah, yup that would make sense, glad you were able to fix it.

You could either 
1. Change the API keys in the source files and build `bundle exec jekyll serve` to update `_site` (recommended, have to change two files) 
(or)
2. Update the API keys in each file (*.html and youtube-api-v3.js) in `_site` though you would need to fix the Google Maps API three times instead of once (not recommended, have to change 4 files, and fix it again if you run the bundle command again)
