### ISSUE TITLE
"Page limit" isn't working.

### ISSUE THREAD

**Issue by snifer1981** [mattwright324/youtube-geofind#4]
"Page limit" isn't working.

**Comment by mattwright324** [comment]
Are you referring to the number of 'pages' in the list at the bottom?

The page limit refers to the number of YouTube API query result pages it performs with a maximum of 50 items per page. The list at the bottom is configured to display 10 items per page. You can verify by checking the total item count in the list as long as it's equal to or less than 50 * page limit.

However, the page limit may only do 1 page of results because your query is too specific. If your query is too specific, in an area that is likely to have few videos, or the time frame too short, there just may not be enough results to come back.

**Comment by snifer1981** [comment]
Then you're right, it's working the way you're saying. It's just users don't know the page size, i was assuming 1 page equals the "show XX entries" value. May be the list should say "1 page (50 entries)", "2 pages (100 entries)", etc.

You can close this issue now, thanks for your reply.

**Comment by mattwright324** [comment]
41e3178dc3173ee35c8e27f76075155f84edada5 added additional comment below page limit selection box to let you know the 50 max-items per page
