### ISSUE TITLE
feature request: langange filter

### ISSUE THREAD

**Issue by FlashJunior** [mattwright324/youtube-geofind#8]
Is it possible to add a language filter?
Here in Switzerland we have 4 Languages and i would like to filter Location + Video-Language.

Cheers
Martin

**Comment by mattwright324** [comment]
Hey @FlashJunior,

I don't think this is possible unfortunately... there does appear to be a parameter `relevanceLanguage` that you can put an [ISO 639-1 code](http://www.loc.gov/standards/iso639-2/php/code_list.php) into but it doesn't work like you would expect. I tried it and it doesn't filter results. 

- [StackOverflow - What does the 'relevanceLanguage' parameter really do?](https://stackoverflow.com/q/55455028/2650847)

There is also a `regionCode` parameter but not so helpful when you already have a region based on location coordinates and radius and also not helpful for your situation where multiple languages are in the same region/country. 

I think a language filter would be a cool thing to add if it worked.

**Comment by jschanker** [comment]
Hi @mattwright324,

Thanks for creating this great tool!  I was interested in seeing this feature too.  Although I can't find something in the YouTube APIs that would exclusively provide results in the specified language, perhaps you could add a dropdown menu that's used to dynamically filter the results that you received by language?  The dropdown could have options for each language specified by at least one video (using [`video.snippet.defaultAudioLanguage`](https://developers.google.com/youtube/v3/docs/videos#snippet.defaultAudioLanguage) or [`video.snippet.defaultLanguage`](https://developers.google.com/youtube/v3/docs/videos#snippet.defaultLanguage) ) with numbers in parentheses designating the number of results for the specified language and an unspecified category for unclassified videos.  Something like:

All (50)
en (20)
fr (10)
sp (5)
Unspecified (15) 

I was looking to create a PR, but it seems it'd take me a little time to investigate how to build the project locally to test.

**Comment by mattwright324** [comment]
That would be a decent alternative idea @jschanker!

Though, I could also create some kind of documentation for building the site to work on it locally. It is built with Jekyll and bundler locally. Generally I think the steps would be...

1. Clone the project
2. Install Ruby and Jekyll https://jekyllrb.com/docs/installation/windows/
3. Command Prompt cd to the project directory
  a. Run this only the first time to get bundler `bundle install`
  b. When starting/doing development run `bundle exec jekyll serve`. Live local version should be running at http://localhost:4000. Jekyll works such that changes to files during development are immediately published to the local version meaning just need to refresh your browser tab to get the changes you made.

This app runs with GitHub Pages which uses Jekyll.

**Comment by jschanker** [comment]
Great, thanks!  In case this is useful, I put together a quick-and-dirty language filter (See https://github.com/mattwright324/youtube-geofind/pull/9).  Feel free to clean it up as desired (or ignore it if it's not helpful :-) )

**Comment by mattwright324** [comment]
Pushed my changes to my `develop` branch if you want to check them out https://github.com/mattwright324/youtube-geofind/commit/86ccc8c7ab19b50f571844344a5e3348a0b7ead1

**Comment by jschanker** [comment]
Regarding branches, it appears that I was unable to propose a new one since I don't have write access to your repository.  I'd definitely recommend leaving at least one alternate branch for development if you want people to be able to contribute so new features could be worked on and tested until they're ready to be deployed.   Maybe also keep one for language filtering for additional changes (e.g., exporting to CSV, updating map, showing language names instead of codes, etc.)?

Regarding your changes, they look good to me.  Using database filtering is definitely more robust than my workaround of showing/hiding `div`s with the results in the appropriate languages.  I haven't used `DatabaseTables` in previous projects so I went with what was quicker.  But this was problematic (e.g., potentially incorrectly filtered results when user goes through the pages of results because no event listener to update videos on button clicks, number of items not reflected in filter count at bottom and any future breaking changes).

A few related observations about sorting:

* `Object.keys` is not required to preserve the insertion order of the keys so the sorting function https://github.com/mattwright324/youtube-geofind/commit/86ccc8c7ab19b50f571844344a5e3348a0b7ead1#diff-4948a9bb07718b8acf1e0bdefcc867817c91f298df488f4c08f74b5528b27129R126 you created could technically fail.  But it should work in practice, and the 2020 spec requires this since the keys for language codes will not be numeric.  See: https://stackoverflow.com/questions/30076219/does-es6-introduce-a-well-defined-order-of-enumeration-for-object-properties/30919039#30919039.
* `Unspecified` now displays as `undefined` and won't necessarily appear last.
* If you eventually display the language names but sort by their codes, it's possible the names won't appear alphabetically. 

Anyway, thanks again for your work on this!

**Comment by mattwright324** [comment]
I do think that's a good idea. I will keep the `develop` branch to be available for you and others to contribute / pr / merge into before merging to master which GitHub Pages uses for the final deployed version. I think I should create some sort of CONTRIBUTING.md and wiki page about local development (similar to my quick Jekyll steps earlier). Just taking a look at other CONTRIBUTING in other projects to try and get an idea of what it should look like... and possibly do the same for my other projects youtube-metadata and youtube-comment-suite.

Depending how active someone wants to be on the project I could give access otherwise would just be from a fork into develop like you had done.

- I think the sorting will work fine, good to know they can't start with a number or be just a number.
- Could go either way on the undefined/unspecified but guess I preferred the way I changed it for now.
- In my other project YouTube Metadata, I did create a language/country code translator for that but some of the translated names can be long so not sure about how good that would look in the select box. Could alternatively just display the translation in the datatable/marker popup detail and just have the plain code in the select box.
  - https://github.com/mattwright324/youtube-metadata/blob/master/js/iso-639-translator.js
  - https://github.com/mattwright324/youtube-metadata/blob/master/js/iso-3166-translator.js
  - https://github.com/mattwright324/youtube-metadata/blob/master/js/bcp-47-translator.js

**Comment by mattwright324** [comment]
I have added the `relevanceLanguage` option though again it doesn't filter results but makes it more likely for videos with those languages to come back. Must set the sort option to `relevance` for it to work and it does seem to influence the results fairly well based on returned language results.
